name: Fetch Data

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  screenshots:
    name: Fetch the data
    runs-on: ubuntu-latest
    steps:
      - name: Perform Checkout
        uses: actions/checkout@v4

      - name: Run checker
        run: ./fetch_data.sh

      - name: Commit data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Data updated
